-- Build
-- Tables
source ./sql/tables/create_people.sql
source ./sql/tables/create_series.sql
source ./sql/tables/create_movies.sql
source ./sql/tables/create_votes.sql
source ./sql/tables/create_trackers.sql
source ./sql/tables/create_movie_trackers.sql
-- Views
source ./sql/views/create_movies_in_series_vw.sql
source ./sql/views/create_movies_votes_vw.sql
source ./sql/views/create_good_votes_vw.sql
source ./sql/views/create_bad_votes_vw.sql
source ./sql/views/create_rating_vw.sql
source ./sql/views/create_trackers_vw.sql
source ./sql/views/create_dn_movies_votes_vw.sql