-- Build
-- Tables
source ./tables/create_people.sql
source ./tables/create_series.sql
source ./tables/create_movies.sql
source ./tables/create_votes.sql
source ./tables/create_trackers.sql
source ./tables/create_movie_trackers.sql
source ./tables/create_images.sql
source ./tables/create_movies_images.sql
-- Views
source ./views/create_movies_images_vw.sql
source ./views/create_series_image_vw.sql
source ./views/create_movies_in_series_vw.sql
source ./views/create_movies_votes_vw.sql
source ./views/create_good_votes_vw.sql
source ./views/create_bad_votes_vw.sql
source ./views/create_rating_vw.sql
source ./views/create_trackers_vw.sql
source ./views/create_dn_movies_votes_vw.sql
source ./views/create_trackers_images_vw.sql
source ./views/create_trackers_main_vw.sql