-- Populate
source ./data_load/insert_people.sql
source ./data_load/insert_series.sql
source ./data_load/insert_movies.sql
source ./data_load/insert_votes.sql
source ./data_load/insert_trackers.sql
source ./data_load/insert_movie_trackers.sql
source ./data_load/insert_images.sql
source ./data_load/insert_movies_images.sql